#!/bin/bash

cd $UHOME;
rm -f vl*;
echo {\"Ubuntu\": > versions;
lsb_release -sr | awk '{print "\"" $1 "\"" ","}' >> versions;
echo \"Python\": { >> vlp;
python3 --version >> vlptmp;
pip list | tail -n +3 >> vlptmp;
cat vlptmp | awk '{print "\"" $1 "\"" ":" "\"" $2 "\"," }' > vlptmp2;
sed '$ s/.$//' vlptmp2 >> vlp;
echo }, >> vlp;
echo \"R\": { >> vlR;
R --version | head -n 1 | awk '{print $1 " " $3}' >> vlRtmp;
Rscript -e 'as.data.frame(installed.packages())[3]' | tail -n +2 >> vlRtmp;
cat vlRtmp | awk '{print "\"" $1 "\"" ":" "\"" $2 "\"," }' > vlRtmp2;
sed '$ s/.$//' vlRtmp2 >> vlR;
echo }} >> vlR;
cat vlp >> versions;
cat vlR >> versions;
