#!/bin/bash

# Create folders for R&Python packages
cd $JUPYTER_WORKDIR

export R_PLUGIN_PATH=$(R --version | head -n 1 | awk '{print $1 "-" $3}')
export PYTHON_PLUGIN_PATH=$(python3 --version | awk '{print $1 "-" $2}')

mkdir -p $R_PLUGIN_PATH $PYTHON_PLUGIN_PATH ../.pip
cd ..

# Set Python&R libraries.
printf "[global]\ntarget=$PYTHON_PLUGIN_PATH\n" > .pip/pip.conf
echo ".libPaths(c('$R_PLUGIN_PATH', .libPaths()))" >> /etc/R/Rprofile.site

# Set jupyter paths.
echo "setwd('$JUPYTER_WORKDIR')" >> /etc/R/Rprofile.site
echo "c.NotebookApp.notebook_dir = '$JUPYTER_WORKDIR'" >> \
    .jupyter/jupyter_notebook_config.py